# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  pull_request:
    branches: 
      - master
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: yarn
    - run: yarn nx workspace-lint
    - name: Run validate
      shell: bash
      run: |
        if [[ $GITHUB_BASE_REF ]]
        then
          export NX_BASE=remotes/origin/$GITHUB_BASE_REF
        else
          export NX_BASE=$(git rev-parse HEAD~1)
        fi
        echo "Base => $NX_BASE"
        yarn format:check --base=$NX_BASE
        yarn affected:lint --base=$NX_BASE
        yarn affected:test --base=$NX_BASE
        yarn affected:build --base=$NX_BASE --prod
